#!/bin/bash 

# Very useful for stash handling
function show-stash() 
{
    git stash show -p stash@{$1};
}

function stash-len() 
{
    git stash list | wc -l;
}

function drop-stash() 
{
    git stash drop stash@{$1};
}

# Git Commands
# Add and Commit are used as functions
alias gaa='git add *'
alias gd='git diff' 
alias gdc='git diff --cached' 
alias gl='git log'
alias glo='git log --oneline'
alias gp='git pull' 
alias gst='git status' 
alias gpo='git push origin main'
alias gs='git status'
alias gr='git reflog'
alias gc='git commit -m'
alias gcf='git config --list'
